language: generic
sudo: required
services:
  - docker
before_install:
  - docker build -t radostchipeva/docker-react-test -f Dockerfile.dev .
script:
  - docker run -e CI=true radostchipeva/docker-react-test npm run test
